# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hernandes
email: midia.matheus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  That's my website/blog, I write somethings about me and the awesome code world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mhernandes.github.io" # the base hostname & protocol for your site
facebook: mthernandes
instagram: mt_hernandes
twitter: mt_hernandes
github: mhernandes
spotify: mhernandes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

site_links:
    - title: home
      url: / 
    - title: blog
      url: /blog
    - title: about
      url: /about

color: gray
lang: en

exclude: ['package.json', 'dev', 'node_modules', 'screenshots', 'gulpfile.js', 'back*.*', 'LICENSE.md', 'README.md']

sass:
  sass_dir: dev/scss