# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pineb | Desenvolvimento de um jeito diferente
email: midia.matheus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um blog voltado ao desenvolvimento web, programação e algumas ideias bacanas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pineb.com.br" # the base hostname & protocol for your site
twitter_username: devhernandes
github_username:  devmath

# Build settings
markdown: kramdown
permalink: /:title/
