# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hernandes
email: midia.matheus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  That's my website/blog, I write somethings about me and the awesome code world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mhernandes.github.io" # the base hostname & protocol for your site
facebook: mthernandes
instagram: mt_hernandes
twitter: mt_hernandes
github: mhernandes
spotify: mhernandes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

series:
    - title: title

site_links:
    - title: articles
      url: / 
      
    - title: projects
      url: /projects

color: gray
lang: en

exclude: ['package.json', 'dev', 'node_modules', 'screenshots', 'gulpfile.js', 'back*.*', 'LICENSE.md', 'README.md']

sass:
  sass_dir: dev/scss

projects:
  - name: mustang.js
    github: 'https://github.com/mhernandes/mustang-js'
    
  - name: shield-scss
    github: 'https://github.com/mhernandes/shield-scss'
    
  - name: keyguard
    github: 'https://github.com/mhernandes/keyguard'
    
  - name: start-user
    github: 'https://github.com/mhernandes/start-user'
    
  - name: awesome-movies
    github: 'https://github.com/mhernandes/awesome-movies'
    
  - name: diametrum
    github: 'https://github.com/mhernandes/diametrum'
    
  - name: favorite-articles
    github: 'https://github.com/mhernandes/favorite-articles'
    
  - name: front-challenges
    github: 'https://github.com/mhernandes/front-challenges'